### ISSUE TITLE
Demo doesn't seem to be working

### ISSUE THREAD

**Issue by asmith26** [Farama-Foundation/CrowdPlay#1]
http://retro-videogame-study.org/

![Screenshot from 2023-08-11 20-25-17](https://github.com/Farama-Foundation/CrowdPlay/assets/6988036/40a59c93-6a4c-40cf-9c13-7b799ee8220a)

I also get the same as the above image when I try to run this [locally](https://farama-foundation.github.io/CrowdPlay/running_crowdplay/get_started.html).

Many thanks for any help :)

**Comment by mgerstgrasser** [comment]
Thank you for flagging this, @asmith26 . Seems an update to a dependency of a dependency caused an incompatibility in the backend. This should be fixed now! (But let me know in case you still have any issues.)

**Comment by asmith26** [comment]
Can confirm this works for me locally, thanks!
